packages:
  - '*/src'

catalog:
  '@slidev/cli': ^52.1.0
  '@slidev/theme-default': ^0.25.0
  playwright-chromium: ^1.54.2
  prettier: ^3.6.2
  prettier-plugin-slidev: ^1.0.5
  vue: ^3.5.18

onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - vue-demi
