packages:
  - '*/src'

catalog:
  '@slidev/cli': ^51.8.2
  '@slidev/theme-default': ^0.25.0
  playwright-chromium: ^1.53.0
  prettier: ^3.5.3
  prettier-plugin-slidev: ^1.0.5
  vue: ^3.5.16

onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - vue-demi
