packages:
  - '*/src'

catalog:
  '@slidev/cli': ^0.50.0-beta.5
  '@slidev/theme-default': latest
  playwright-chromium: ^1.48.2

onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
  - vue-demi
